---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-components
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: infra-components
spec:
  project: argo-management
  source:
    repoURL: 'https://github.com/Jitmisra/newargo3'
    targetRevision: main
    path: ./argo/infra
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - Validate=true
    - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 10
