# ============LICENSE_START=======================================================
#  Copyright (c) 2025 Deutsche Telekom
# ================================================================================
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
#  SPDX-License-Identifier: Apache-2.0
# ============LICENSE_END=========================================================

global:
  imageRegistry: docker.io
  imagePullSecrets:
    - artifactory-docker-secret
  defaultStorageClass: nfs
  storageClass: nfs
  serviceMesh:
    enabled: true
  ingress:
    post_addr: ""
    dns_zone: "simpledemo.onap.org"

serviceMesh:
  envVariable:
    SERVICE_MESH_ENABLED: true

imagePullSecrets:
  - name: artifactory-docker-secret

tests:
  testEnvName: "main"
  smokeTests:
    artifacts:
      storageClassName: nfs
    testsuite:
      name: onap-testsuite
      cron: 0 6 * * *
      # Testsuite job is going to be killed after 6 hours
      # if it doesn't end by itself. That prevents an issue
      # with blocked cronjobs executions
      testsuiteJobActiveDeadlineSeconds: 21600
      # Tests listed below will be included into testsuite
      # Important: test here is no a test name but a key from `tests.tests` value dictionary
      # We are going to range through list below, get object from `tests.tests` dictionary,
      # verify if it's enabled and then add it into testsuite. So user at the end has to
      # remember only on one place to enable/disable test. But thanks to that we are able
      # to modify order, presence of tests on testsuite but also to include some tests
      # which are not a part of given helm package (so for example if that helm is a dependency
      # of other package)
      tests:
      - basicCps
      - basicOnboard
      - basicNetwork
      - basicCds
      - basicSdnc
      - basicCnfMacro
      - controlPanelSmokeTest
      - aaiInitialDataSetup
      - serviceWithoutResource
      - addDeletePnfInRunningService
      - pnfWithVesEvent
      - pnfWithoutVesEvent
      - pnfMacro
      - basicPrh
      - checkTimeSync
      - basicStatus
      - basicKafka
      - addDeleteCnfMacro
      - policyFramework
      - vesPublish

testkube:
  testkube-dashboard:
    apiServerEndpoint: "https://testkube-api.simpledemo.onap.org"
  testkube-api:
    minio:
      storageClassName: nfs
      image:
        registry: docker.io
  mongodb:
    storageClass: nfs
  nats:
    config:
      jetstream:
        fileStore:
          pvc:
            storageClassName: nfs
      resolver:
        pvc:
          storageClassName: nfs
